---
exp_name: BGGN
exp_dir: exp/BGGN
runner: GranRunner
use_horovod: false
use_gpu: true
# use_gpu: false
# available_gpu: "0"
# available_gpu: "2,3"
device: cuda:0
gpus: [0]
# gpus: [0,1]
seed: 1234
# search: true
# search: false
dataset:
  # loader_name: BGGNData
  train_loader_name: TrainData
  test_loader_name: TestData
  name: Youshu
  data_path: data
  node_order: DFS # k_core/BFS/degree_decent
  train_ratio: 0.8
  dev_ratio: 0.2
  num_subgraph_batch: 2 # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: false
  is_save_split: false  
  is_sample_subgraph: true # set to true if you want to sample subgraphs
  # is_sample_subgraph: false # set to true if you want to sample subgraphs
  is_overwrite_precompute: false
  num_users: 8039
  num_bundles: 4771
  num_items: 32770
model:
  name: BGGNMixtureBernoulli
  num_mix_component: 20
  is_sym: true
  block_size: 1
  sample_stride: 1
  max_num_nodes: 300 
  hidden_dim: 64
  embedding_dim: 64
  user_embedding_dim: 64
  item_embedding_dim: 64
  num_GNN_layers: 2
  num_GNN_prop: 1
  num_canonical_order: 1
  dimension_reduce: true  
  has_attention: true
  edge_weight: 1.0e+0
train:
  optimizer: Adam  
  lr_decay: 0.1
  lr_decay_epoch: [100000000] # no decay
  # lr_decay_epoch: [2,2,2] 
  lr_decay_size: 1 
  num_workers: 16
  max_epoch: 50
  # max_epoch: 200
  # max_epoch: 10
  # batch_size: 16
  batch_size: 8
  # batch_size: 1
  # display_iter: 10
  # display_iter: 100
  display_iter: 1000
  snapshot_epoch: 5
  valid_epoch: 50
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 5000
  resume_dir: # exp/BGGN/your_exp_folder
  resume_model: model_snapshot_0005000.pth
  bpr_weight: 1
  tsne_dir: ./tsne
test:  
  # batch_size: 20
  batch_size: 1
  # topk: 1
  topk: 10
  topk1: 5
  # num_workers: 0
  num_workers: 16
  num_test_gen: 183 # number of generated samples  
  is_vis: true
  is_single_plot: false # visualize `num_vis` samples in a single image
  is_test_ER: false # test Erdos-Renyi baseline
  num_vis: 20
  vis_num_row: 5 # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true  
  test_model_dir: /data/changjianxin/BGGN/exp/Youshu_20200829_194945_124792
  test_model_name: model_snapshot_0000050.pth
